version: 1
frontend:
  phases:
    # We leave commands empty because we don't need to compile anything (npm install, npm run build, etc.)
    build:
      commands: []
  artifacts:
    # IMPORTANT: This tells Amplify your index.html is in the root folder, not in a 'build' or 'public' folder
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
